---
apiVersion: v1
kind: Namespace
metadata:
  name: telepresence-demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend-service
  name: backend-service
  namespace: telepresence-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: bzon/telepresence-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 16Mi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: frontend-service
  name: frontend-service
  namespace: telepresence-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        env:
        - name: BACKEND_SERVICE_ENDPOINT
          value: backend-service:8080
        image: bzon/telepresence-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
