---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-service
  name: backend-service
  namespace: telepresence-demo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: backend-service
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
  namespace: telepresence-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: frontend-service
  type: LoadBalancer
